"""initial schema

Revision ID: 526ef4fe192e
Revises: 
Create Date: 2026-06-24 13:14:27.429387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526ef4fe192e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(length=80), nullable=False),
    sa.Column('annual_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_avg_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=False),
    sa.Column('risk_profile', sa.String(length=20), nullable=False),
    sa.Column('relationship_since', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('min_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_credit_score', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=12), nullable=False),
    sa.Column('product_id', sa.String(length=12), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('balance_or_outstanding', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_customer_id'), 'holdings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_holdings_product_id'), 'holdings', ['product_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=12), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_holdings_product_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_customer_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_table('products')
    op.drop_table('customers')
    # ### end Alembic commands ###
